name: data_sync_desktop
description: Aviation business data sync CLI - syncs Google Places data to MongoDB.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mongo_dart: ^0.8.2
  args: ^2.4.0
  string_similarity: ^2.0.0
  excel: ^2.1.0
  http: ^0.13.5
  html: ^0.15.3
  us_states: ^1.0.3

dev_dependencies:
  test: ^1.22.0

dependency_overrides:
  archive: ^3.6.0
